# Generated by Django 3.1.7 on 2021-03-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_universityrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
