# Generated by Django 3.1.7 on 2021-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_universityname'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityrecord',
            name='reco',
            field=models.BooleanField(null=True),
        ),
    ]
