# Generated by Django 3.1.7 on 2021-03-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_universityrecord_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityrecord',
            name='financial',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='universityrecord',
            name='info',
            field=models.BooleanField(null=True),
        ),
    ]
