# Generated by Django 3.1.7 on 2021-03-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_auto_20210320_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityrecord',
            name='extra',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='universityrecord',
            name='test',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='universityrecord',
            name='transcripts',
            field=models.BooleanField(null=True),
        ),
    ]
