# Generated by Django 3.1.7 on 2021-03-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_essay'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='univ_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
